### ISSUE TITLE
p.181 評價("comment")未填不會觸發error? (Module 11)

### ISSUE THREAD

**Issue by youthhng** [its-django/mysite#16]
您好：

在p.181頁中共有三個欄位：
- 留言者
- 電子信箱
- 評價

在所有的2x2x2=8種組合中，我發現
- 只填寫「留言者」、「電子信箱」
- 未填「評價」
並不會觸發error，而且可以正常寫入DB。

在檢查了 http://127.0.0.1:8000/admin/restaurants/comment/5/ 的資料結果，
Content值的確是空的，且"Content"這個欄位本身是粗體 (必填)。

是因為"Content"是textarea，所以可以允許為blank的緣故嗎？
感謝～

**Comment by myyang** [comment]
Hi, 

由於我們在範例中宣告的content欄位 ( `content=models.CharField(max_length=255)` )中並未使用 `null=True` 這個選項，所以django不能接受”空值(null)”

欄位選項中的 `null=True` 和 `blank=True` 是不同的，null是指資料庫能不能接受空值，blank則是指表單驗證時能不能接受空值


但你描述的行為似乎不符合預期… 

請你檢查你的欄位是否有加入其他選項，或content的值是nul還l是空白字串？

---
Yours sincerely, 
MengYing Yang

**Comment by youthhng** [comment]
您好：

抱歉我發現原因了......我的comment的textarea不知何時輸入了兩個空白鍵 (space)，
導致畫面上雖然看不見內容，但實際上仍存進了DB。
而且既有有問題的資料，的確也存進了兩個空白.....

感謝您的回覆 Orz
